const auth = {
    SIGN_IN: 'SIGN_IN',
    LOG_OUT: 'LOG_OUT',
    CREATE_USER_ACCOUNT: 'SIGN_UP',
    VERIFY_USER_ACCESS: 'VERIFY_USER_ACCESS',
    VERIFY_ADMIN_ACCESS: 'VERIFY_ADMIN_ACCESS',
    // VERIFY_EMAIL_STATE: 'VERIFY_EMAIL_STATE',
    UPDATE_CREDENTIALS: 'UPDATE_CREDENTIALS',
    IS_USER_CREATED: 'IS_USER_CREATED'
};

export default auth;